AllCops:
  TargetRubyVersion: 2.2
  Exclude:
    - 'lib/asciidoctor/inline_parser/asciidoctor_grammar.rb'
    - 'node_modules/**/*.rb'
    - 'build/**/*'

Metrics/LineLength:
  Max: 120
  Exclude:
    - 'test/*'

Style/MethodDefParentheses:
  EnforcedStyle: require_no_parentheses

Style/SymbolArray:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - 'test/*'

Metrics/ModuleLength:
  Max: 200

Metrics/MethodLength:
  Max: 20
