# Autogenerated from a Treetop grammar. Edits may be lost.


module AsciidoctorMenuGrammar
  include Treetop::Runtime

  def root
    @root ||= :menu
  end

  module Menu0
    def menu_target
      elements[1]
    end

    def menu_content
      elements[3]
    end

  end

  def _nt_menu
    start_index = index
    if node_cache[:menu].has_key?(index)
      cached = node_cache[:menu][index]
      if cached
        node_cache[:menu][index] = cached = SyntaxNode.new(input, index...(index + 1)) if cached == true
        @index = cached.interval.end
      end
      return cached
    end

    i0, s0 = index, []
    if (match_len = has_terminal?('menu:', false, index))
      r1 = instantiate_node(SyntaxNode,input, index...(index + match_len))
      @index += match_len
    else
      terminal_parse_failure('\'menu:\'')
      r1 = nil
    end
    s0 << r1
    if r1
      r2 = _nt_menu_target
      s0 << r2
      if r2
        if (match_len = has_terminal?('[', false, index))
          r3 = true
          @index += match_len
        else
          terminal_parse_failure('\'[\'')
          r3 = nil
        end
        s0 << r3
        if r3
          r4 = _nt_menu_content
          s0 << r4
          if r4
            if (match_len = has_terminal?(']', false, index))
              r5 = true
              @index += match_len
            else
              terminal_parse_failure('\']\'')
              r5 = nil
            end
            s0 << r5
          end
        end
      end
    end
    if s0.last
      r0 = instantiate_node(Menu,input, i0...index, s0)
      r0.extend(Menu0)
    else
      @index = i0
      r0 = nil
    end

    node_cache[:menu][start_index] = r0

    r0
  end

  def _nt_menu_target
    start_index = index
    if node_cache[:menu_target].has_key?(index)
      cached = node_cache[:menu_target][index]
      if cached
        node_cache[:menu_target][index] = cached = SyntaxNode.new(input, index...(index + 1)) if cached == true
        @index = cached.interval.end
      end
      return cached
    end

    s0, i0 = [], index
    loop do
      if has_terminal?(@regexps[gr = '\A[^\\[]'] ||= Regexp.new(gr), :regexp, index)
        r1 = true
        @index += 1
      else
        terminal_parse_failure('[^\\[]')
        r1 = nil
      end
      if r1
        s0 << r1
      else
        break
      end
    end
    if s0.empty?
      @index = i0
      r0 = nil
    else
      r0 = instantiate_node(MenuTarget,input, i0...index, s0)
    end

    node_cache[:menu_target][start_index] = r0

    r0
  end

  def _nt_menu_content
    start_index = index
    if node_cache[:menu_content].has_key?(index)
      cached = node_cache[:menu_content][index]
      if cached
        node_cache[:menu_content][index] = cached = SyntaxNode.new(input, index...(index + 1)) if cached == true
        @index = cached.interval.end
      end
      return cached
    end

    s0, i0 = [], index
    loop do
      i1 = index
      if (match_len = has_terminal?('\]', false, index))
        r2 = instantiate_node(SyntaxNode,input, index...(index + match_len))
        @index += match_len
      else
        terminal_parse_failure('\'\\]\'')
        r2 = nil
      end
      if r2
        r2 = SyntaxNode.new(input, (index-1)...index) if r2 == true
        r1 = r2
      else
        if has_terminal?(@regexps[gr = '\A[^\\]]'] ||= Regexp.new(gr), :regexp, index)
          r3 = true
          @index += 1
        else
          terminal_parse_failure('[^\\]]')
          r3 = nil
        end
        if r3
          r3 = SyntaxNode.new(input, (index-1)...index) if r3 == true
          r1 = r3
        else
          @index = i1
          r1 = nil
        end
      end
      if r1
        s0 << r1
      else
        break
      end
    end
    r0 = instantiate_node(MenuContent,input, i0...index, s0)

    node_cache[:menu_content][start_index] = r0

    r0
  end

end

class AsciidoctorMenuGrammarParser < Treetop::Runtime::CompiledParser
  include AsciidoctorMenuGrammar
end

